### ISSUE TITLE
Event push notifications

### ISSUE THREAD

**Issue by Reaxt** [Auros/VRAtlas.Web#10]
**Is your feature request related to a problem? Please describe.**
I would like to ensure I do not miss any upcoming events that excite me, or forget to attend them.

**Describe the solution you'd like**
A easy way to do this could be to have the website use web push notifications in order to notify users when events they follow are occuring.

**Additional context**
Email notifications could be nice too.

**Comment by Auros** [comment]
Looking into browser `Notification` API, this seems very doable.

Email support is planned and can be implemented with relative ease on the back end. The only problem is finding an email provider that:
A.) Isn't Expensive
B.) Doesn't get blocked by emails
C.) Is relatively sane to use

**Comment by Auros** [comment]
Implemented, currently Live
