### ISSUE TITLE
Support for video flyer formats (MP4, WEBM)

### ISSUE THREAD

**Issue by jgreenemi** [Auros/VRAtlas.Web#30]
**Is your feature request related to a problem? Please describe.**
When uploading flyers to VRAtlas, I want to upload a video file as the flyer instead of an image, but I am only allowed to upload an image.

**Describe the solution you'd like**
Support for MP4 format flyers in upload, and automatic looped playback of the flyers on event detail pages.

**Additional context**
I've mentioned also the format of WEBM, though I've only ever seen it used once for event flyers in the VRC space in the last ~2 years.

**Comment by Auros** [comment]
I'll add this relatively soon, but I'd like to detail the planned implementation:

Normal image flyers will still be required:
* Useful for embedding, as the video would need to be manually clicked to start playing in an embed, making it unpractical.
* Great to fall back on if a user has requested reduced data usage.
* Easier to implement on the API

The upload will allow both a `.mp4` and a `.webm` file, and the server will generate a new `.mp4` and `.webm` file with the audio tracks removed (required for auto-play to reliably work on most browsers).

The website will prefer `.webm` when selecting the event media, and fallback onto `.mp4` if it's on an unsupported browser. [macOS only very recently got `.webm` support, and Safari on iOS still only has partial support](https://caniuse.com/webm).

For embeds and when reduced data usage is requested, it will fallback to the image version of the flyer.

I was thinking `10 MB` for the maximum file upload size for video flyers. Do you think this would be too high/low?

**Comment by Auros** [comment]
![image](https://user-images.githubusercontent.com/41306347/225573959-94b8c1e7-ede2-42d6-a670-827c485bcda9.png)

Implemented and currently live!
