### ISSUE TITLE
Discord Embed Bug

### ISSUE THREAD

**Issue by FoxeVR** [Auros/VRAtlas.Web#34]
When sending a group link via discord, the description text of the group shows in plain text, when it probably shouldn't show the link attached to the text. Example below

![Capture](https://user-images.githubusercontent.com/126199768/226743606-0ebd8142-2661-4666-8fe8-5e5dff426367.PNG)

**Comment by Auros** [comment]
This is one of the quirks of how Markdown works. I just learned that embed links can't be generated unless the account posting it is a bot. I'll look into a way for stripping out special markdown elements like links.

**Comment by Auros** [comment]
Resolved in #35
